import IISUchetMedosmotrov2ПодразделенияEController from '../i-i-s-uchet-medosmotrov2-подразделения-e';

var IISUchetMedosmotrov2ПодразделенияENewController = IISUchetMedosmotrov2ПодразделенияEController;
export default IISUchetMedosmotrov2ПодразделенияENewController;
