//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.UchetMedosmotrov2
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Должности.
    /// </summary>
    // *** Start programmer edit section *** (Должности CustomAttributes)

    // *** End programmer edit section *** (Должности CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ДолжностиE", new string[] {
            "Наименование as \'Наименование\'",
            "Подразделения as \'Подразделения\'",
            "Подразделения.Наименование as \'Наименование\'"}, Hidden=new string[] {
            "Подразделения.Наименование"})]
    [MasterViewDefineAttribute("ДолжностиE", "Подразделения", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Наименование")]
    [View("ДолжностиL", new string[] {
            "Наименование as \'Наименование\'",
            "Подразделения.Наименование as \'Наименование\'"})]
    public class Должности : ICSSoft.STORMNET.DataObject
    {
        
        private string fНаименование;
        
        private IIS.UchetMedosmotrov2.Подразделения fПодразделения;
        
        // *** Start programmer edit section *** (Должности CustomMembers)

        // *** End programmer edit section *** (Должности CustomMembers)

        
        /// <summary>
        /// Наименование.
        /// </summary>
        // *** Start programmer edit section *** (Должности.Наименование CustomAttributes)

        // *** End programmer edit section *** (Должности.Наименование CustomAttributes)
        [StrLen(255)]
        public virtual string Наименование
        {
            get
            {
                // *** Start programmer edit section *** (Должности.Наименование Get start)

                // *** End programmer edit section *** (Должности.Наименование Get start)
                string result = this.fНаименование;
                // *** Start programmer edit section *** (Должности.Наименование Get end)

                // *** End programmer edit section *** (Должности.Наименование Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Должности.Наименование Set start)

                // *** End programmer edit section *** (Должности.Наименование Set start)
                this.fНаименование = value;
                // *** Start programmer edit section *** (Должности.Наименование Set end)

                // *** End programmer edit section *** (Должности.Наименование Set end)
            }
        }
        
        /// <summary>
        /// Должности.
        /// </summary>
        // *** Start programmer edit section *** (Должности.Подразделения CustomAttributes)

        // *** End programmer edit section *** (Должности.Подразделения CustomAttributes)
        [PropertyStorage(new string[] {
                "Подразделения"})]
        [NotNull()]
        public virtual IIS.UchetMedosmotrov2.Подразделения Подразделения
        {
            get
            {
                // *** Start programmer edit section *** (Должности.Подразделения Get start)

                // *** End programmer edit section *** (Должности.Подразделения Get start)
                IIS.UchetMedosmotrov2.Подразделения result = this.fПодразделения;
                // *** Start programmer edit section *** (Должности.Подразделения Get end)

                // *** End programmer edit section *** (Должности.Подразделения Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Должности.Подразделения Set start)

                // *** End programmer edit section *** (Должности.Подразделения Set start)
                this.fПодразделения = value;
                // *** Start programmer edit section *** (Должности.Подразделения Set end)

                // *** End programmer edit section *** (Должности.Подразделения Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ДолжностиE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ДолжностиE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ДолжностиE", typeof(IIS.UchetMedosmotrov2.Должности));
                }
            }
            
            /// <summary>
            /// "ДолжностиL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ДолжностиL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ДолжностиL", typeof(IIS.UchetMedosmotrov2.Должности));
                }
            }
        }
    }
}
